server:
# PORT will be sent in CMD
    port: ${PORT:0}

spring:
    application:
        name: albums-ws
    devtools:
        restart:
            enabled: true
    # H2 Config
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                # enable remote access
                web-allow-others: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    config:
        import: optional:configserver:http//localhost:8888

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

management:
    endpoints:
        web:
            exposure:
                include: "*"

# setup eureka server settings
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        # spring.application.instance_id will be sent in CMD
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file:
      name: services/Albums/albums-ws.log