server:
  port: 8888

spring:
  application:
    name: ConfigServer
  profiles:
    active: native #native file system


  cloud:
    bus:
      enabled: true
    config:
      server:
        native:
          searchLocations: file:///${user.home}/Desktop/Projects/Photo App/PhotoAppConfig/PhotoAppConfiguration
        git:
          uri: https://github.com/OlaAref/PhotoAppConfiguration
          username:
          password:
          clone-on-start: true
          default-label: main #default branch name

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"





