server:
  port: 8082

spring:
  application:
    name: api-gateway
  # automatically mapping
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

# setup eureka server settings
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
