server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # automatically routing
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # manually routing
#      routes:
#        - id: users-status-check
#          uri: lb://users-ws #load balance :// spring application name
#          predicates:
#            - Method=GET
#            - Path= /users/status/checks
#          filters:
#            - RemoveRequestHeader= Cookie

# setup eureka server settings
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
