server:
  port: 0

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true

# setup eureka server settings
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

