server:
  port: ${PORT:0}

spring:
  application:
    name: account-ws
  devtools:
    restart:
      enabled: true
  config:
    import: optional:configserver:http//localhost:8888

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

# setup eureka server settings
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

